# awx-postgres-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
type: Opaque
stringData:
  host: "awx-postgres-15"
  port: "5432"
  database: "awx"
  username: "awx"
  password: "changeme-strong-password"
  type: "managed"
